### ISSUE TITLE
Releasing this in the form of a CLI utility

### ISSUE THREAD

**Issue by Zirro** [jakobhellermann/piechart#3]
I came across this repo while looking for a lightweight CLI utility that takes a few parameters and outputs pie charts. This looks perfect, but appears to only be available as a rust crate. Would you consider releasing a binary with a basic CLI that makes use of this code too? Thank you!

**Comment by jakobhellermann** [comment]
I created a basic cli you can install using `cargo install piechart --features cli` (you can install cargo using [rustup](https://rustup.rs/)).

![image](https://user-images.githubusercontent.com/22177966/115390738-e1522200-a1de-11eb-860e-ef113f39d7d6.png)

**Comment by Zirro** [comment]
Perfect, thanks!
